"""Initial schema: the seven core CTMS tables.

Revision ID: 0001
Revises:
Create Date: Phase 1

Tables are created parent-first so that every foreign key has something to point
at: trials -> sites -> users -> subjects -> visits -> adverse_events ->
audit_logs. `downgrade` drops them in exactly the reverse order.

Hand-written rather than autogenerated, so the schema is reviewable and produces
the same result on every machine. `tests/test_migrations.py` asserts that what
this script builds still matches the SQLModel definitions in `app/models/`, so
the two cannot silently drift apart.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------ trials
    op.create_table(
        "trials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("protocol_number", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("short_title", sa.String(length=200), nullable=False),
        sa.Column("ctri_number", sa.String(length=80), nullable=True),
        sa.Column("ctri_registration_date", sa.Date(), nullable=True),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("indication", sa.String(length=300), nullable=False),
        sa.Column("indication_ayurveda", sa.String(length=300), nullable=True),
        sa.Column("intervention", sa.String(length=500), nullable=False),
        sa.Column("comparator", sa.String(length=300), nullable=True),
        sa.Column("design", sa.String(length=300), nullable=False),
        sa.Column("is_blinded", sa.Boolean(), nullable=False),
        sa.Column("primary_objective", sa.String(length=1000), nullable=True),
        sa.Column("secondary_objective", sa.String(length=1000), nullable=True),
        sa.Column("primary_endpoint", sa.String(length=500), nullable=True),
        sa.Column("sponsor_name", sa.String(length=200), nullable=False),
        sa.Column("sponsor_type", sa.String(length=80), nullable=True),
        sa.Column("target_enrollment", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("actual_end_date", sa.Date(), nullable=True),
        sa.Column("ethics_approval_number", sa.String(length=120), nullable=True),
        sa.Column("ethics_approval_date", sa.Date(), nullable=True),
        sa.Column("regulatory_approval_number", sa.String(length=120), nullable=True),
        sa.Column("regulatory_approval_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trials_protocol_number", "trials", ["protocol_number"], unique=True
    )
    op.create_index("ix_trials_ctri_number", "trials", ["ctri_number"], unique=True)
    op.create_index("ix_trials_status", "trials", ["status"], unique=False)

    # ------------------------------------------------------------------- sites
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("site_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=120), nullable=False),
        sa.Column("pi_name", sa.String(length=200), nullable=False),
        sa.Column("pi_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("target_enrollment", sa.Integer(), nullable=False),
        sa.Column("activation_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trial_id"], ["trials.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sites_trial_id", "sites", ["trial_id"], unique=False)
    op.create_index("ix_sites_site_code", "sites", ["site_code"], unique=False)
    op.create_index("ix_sites_status", "sites", ["status"], unique=False)

    # ------------------------------------------------------------------- users
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        # Nullable: passwords are set in Phase 2, when authentication lands.
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("organization", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_site_id", "users", ["site_id"], unique=False)

    # ---------------------------------------------------------------- subjects
    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("subject_code", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("screening_date", sa.Date(), nullable=True),
        sa.Column("enrollment_date", sa.Date(), nullable=True),
        sa.Column("randomization_date", sa.Date(), nullable=True),
        sa.Column("arm", sa.String(length=30), nullable=False),
        sa.Column("year_of_birth", sa.Integer(), nullable=True),
        sa.Column("age_at_enrollment", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("prakriti", sa.String(length=30), nullable=True),
        sa.Column("completed_date", sa.Date(), nullable=True),
        sa.Column("withdrawal_date", sa.Date(), nullable=True),
        sa.Column("withdrawal_reason", sa.String(length=500), nullable=True),
        sa.Column("screen_failure_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.ForeignKeyConstraint(["trial_id"], ["trials.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_subjects_subject_code", "subjects", ["subject_code"], unique=True
    )
    op.create_index("ix_subjects_trial_id", "subjects", ["trial_id"], unique=False)
    op.create_index("ix_subjects_site_id", "subjects", ["site_id"], unique=False)
    op.create_index("ix_subjects_status", "subjects", ["status"], unique=False)
    op.create_index("ix_subjects_arm", "subjects", ["arm"], unique=False)
    op.create_index("ix_subjects_prakriti", "subjects", ["prakriti"], unique=False)

    # ------------------------------------------------------------------ visits
    op.create_table(
        "visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("visit_name", sa.String(length=120), nullable=False),
        sa.Column("visit_number", sa.Integer(), nullable=False),
        sa.Column("visit_day", sa.Integer(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("actual_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("is_protocol_deviation", sa.Boolean(), nullable=False),
        sa.Column("deviation_description", sa.String(length=1000), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("performed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["performed_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"]),
        sa.ForeignKeyConstraint(["trial_id"], ["trials.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_visits_subject_id", "visits", ["subject_id"], unique=False)
    op.create_index("ix_visits_trial_id", "visits", ["trial_id"], unique=False)
    op.create_index("ix_visits_visit_number", "visits", ["visit_number"], unique=False)
    op.create_index("ix_visits_status", "visits", ["status"], unique=False)
    op.create_index(
        "ix_visits_is_protocol_deviation",
        "visits",
        ["is_protocol_deviation"],
        unique=False,
    )
    op.create_index(
        "ix_visits_performed_by_user_id", "visits", ["performed_by_user_id"], unique=False
    )

    # ---------------------------------------------------------- adverse_events
    op.create_table(
        "adverse_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("ae_number", sa.String(length=40), nullable=False),
        sa.Column("term_verbatim", sa.String(length=300), nullable=False),
        # The free-text narrative the Phase 4 NLP reads.
        sa.Column("description", sa.String(length=4000), nullable=False),
        sa.Column("onset_date", sa.Date(), nullable=False),
        sa.Column("resolution_date", sa.Date(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("is_serious", sa.Boolean(), nullable=False),
        sa.Column("seriousness_criteria", sa.String(length=300), nullable=True),
        sa.Column("causality", sa.String(length=30), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("action_taken", sa.String(length=300), nullable=True),
        sa.Column("related_visit_id", sa.Integer(), nullable=True),
        # MedDRA columns stay empty until Phase 4 codes them.
        sa.Column("meddra_pt_code", sa.String(length=40), nullable=True),
        sa.Column("meddra_pt_term", sa.String(length=200), nullable=True),
        sa.Column("meddra_soc", sa.String(length=200), nullable=True),
        sa.Column("coding_confidence", sa.Float(), nullable=True),
        sa.Column("coding_reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reported_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reported_date", sa.Date(), nullable=True),
        sa.Column("reported_to_ec", sa.Boolean(), nullable=False),
        sa.Column("reported_to_ec_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["coding_reviewed_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["related_visit_id"], ["visits.id"]),
        sa.ForeignKeyConstraint(["reported_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"]),
        sa.ForeignKeyConstraint(["trial_id"], ["trials.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_adverse_events_subject_id", "adverse_events", ["subject_id"], unique=False
    )
    op.create_index(
        "ix_adverse_events_trial_id", "adverse_events", ["trial_id"], unique=False
    )
    op.create_index(
        "ix_adverse_events_site_id", "adverse_events", ["site_id"], unique=False
    )
    op.create_index(
        "ix_adverse_events_ae_number", "adverse_events", ["ae_number"], unique=False
    )
    op.create_index(
        "ix_adverse_events_severity", "adverse_events", ["severity"], unique=False
    )
    op.create_index(
        "ix_adverse_events_is_serious", "adverse_events", ["is_serious"], unique=False
    )
    op.create_index(
        "ix_adverse_events_causality", "adverse_events", ["causality"], unique=False
    )
    op.create_index(
        "ix_adverse_events_outcome", "adverse_events", ["outcome"], unique=False
    )
    op.create_index(
        "ix_adverse_events_related_visit_id",
        "adverse_events",
        ["related_visit_id"],
        unique=False,
    )
    op.create_index(
        "ix_adverse_events_meddra_pt_code",
        "adverse_events",
        ["meddra_pt_code"],
        unique=False,
    )
    op.create_index(
        "ix_adverse_events_meddra_soc", "adverse_events", ["meddra_soc"], unique=False
    )
    op.create_index(
        "ix_adverse_events_reported_by_user_id",
        "adverse_events",
        ["reported_by_user_id"],
        unique=False,
    )

    # -------------------------------------------------------------- audit_logs
    # Append-only by convention: no code path in this project updates or deletes
    # a row here.
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        # Email and role are copied in as text so the log still names who acted
        # even if the user record later changes.
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("user_role", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_label", sa.String(length=200), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.String(length=2000), nullable=True),
        sa.Column("new_value", sa.String(length=2000), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("trial_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=60), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["trial_id"], ["trials.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_timestamp", "audit_logs", ["timestamp"], unique=False)
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_entity_type", "audit_logs", ["entity_type"], unique=False
    )
    op.create_index("ix_audit_logs_entity_id", "audit_logs", ["entity_id"], unique=False)
    op.create_index("ix_audit_logs_trial_id", "audit_logs", ["trial_id"], unique=False)


def downgrade() -> None:
    # Reverse order, so no table is dropped while another still references it.
    op.drop_table("audit_logs")
    op.drop_table("adverse_events")
    op.drop_table("visits")
    op.drop_table("subjects")
    op.drop_table("users")
    op.drop_table("sites")
    op.drop_table("trials")
