"""Add clinical_log_entries table

Revision ID: 04c5b4bf542d
Revises: 4137549cae0a
Create Date: 2026-09-03 18:00:06.424629
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '04c5b4bf542d'
down_revision: str | None = '4137549cae0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_log_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('trial_id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('substance_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column('dose', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('route', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('observation_description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column('linked_visit_id', sa.Integer(), nullable=True),
        sa.Column('linked_ae_id', sa.Integer(), nullable=True),
        sa.Column('correction_of_entry_id', sa.Integer(), nullable=True),
        sa.Column('correction_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('entered_by_user_id', sa.Integer(), nullable=False),
        sa.Column('entered_by_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['correction_of_entry_id'], ['clinical_log_entries.id'], ),
        sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['linked_ae_id'], ['adverse_events.id'], ),
        sa.ForeignKeyConstraint(['linked_visit_id'], ['visits.id'], ),
        sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_log_entries_correction_of_entry_id'), 'clinical_log_entries', ['correction_of_entry_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_entered_by_user_id'), 'clinical_log_entries', ['entered_by_user_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_entry_type'), 'clinical_log_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_linked_ae_id'), 'clinical_log_entries', ['linked_ae_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_linked_visit_id'), 'clinical_log_entries', ['linked_visit_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_site_id'), 'clinical_log_entries', ['site_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_subject_id'), 'clinical_log_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_timestamp'), 'clinical_log_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_clinical_log_entries_trial_id'), 'clinical_log_entries', ['trial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_log_entries_trial_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_timestamp'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_subject_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_site_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_linked_visit_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_linked_ae_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_entry_type'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_entered_by_user_id'), table_name='clinical_log_entries')
    op.drop_index(op.f('ix_clinical_log_entries_correction_of_entry_id'), table_name='clinical_log_entries')
    op.drop_table('clinical_log_entries')
    # ### end Alembic commands ###
