"""Add new subject fields

Revision ID: 4137549cae0a
Revises: 46208917aa57
Create Date: 2026-09-03 17:28:13.965193
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '4137549cae0a'
down_revision: str | None = '46208917aa57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('inclusion_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('subjects', sa.Column('exclusion_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('subjects', sa.Column('eligibility_outcome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('subjects', sa.Column('protocol_version', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('subjects', sa.Column('icf_version', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('subjects', sa.Column('consent_date', sa.DateTime(), nullable=True))
    op.add_column('subjects', sa.Column('consent_obtained_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('subjects', sa.Column('withdrawal_of_consent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('subjects', sa.Column('ethnicity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('subjects', sa.Column('randomized_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('subjects', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subjects_created_by_id'), 'subjects', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_subjects_updated_by_id'), 'subjects', ['updated_by_id'], unique=False)
    bind = op.get_bind()
    if bind and bind.dialect.name != "sqlite":
        op.create_foreign_key('fk_subjects_created_by_id', 'subjects', 'users', ['created_by_id'], ['id'])
        op.create_foreign_key('fk_subjects_updated_by_id', 'subjects', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind and bind.dialect.name != "sqlite":
        op.drop_constraint('fk_subjects_updated_by_id', 'subjects', type_='foreignkey')
        op.drop_constraint('fk_subjects_created_by_id', 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_updated_by_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_by_id'), table_name='subjects')
    op.drop_column('subjects', 'updated_by_id')
    op.drop_column('subjects', 'created_by_id')
    op.drop_column('subjects', 'randomized_by')
    op.drop_column('subjects', 'ethnicity')
    op.drop_column('subjects', 'withdrawal_of_consent')
    op.drop_column('subjects', 'consent_obtained_by')
    op.drop_column('subjects', 'consent_date')
    op.drop_column('subjects', 'icf_version')
    op.drop_column('subjects', 'protocol_version')
    op.drop_column('subjects', 'eligibility_outcome')
    op.drop_column('subjects', 'exclusion_criteria')
    op.drop_column('subjects', 'inclusion_criteria')
    # ### end Alembic commands ###
