import sqlmodel
"""add_suppqual_to_subject

Revision ID: 46208917aa57
Revises: bbb857bc24fb
Create Date: 2026-09-03 08:19:03.294990
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '46208917aa57'
down_revision: str | None = 'bbb857bc24fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('suppqual', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'suppqual')
    # ### end Alembic commands ###
