"""add query fields to visit

Revision ID: ace257f86c3f
Revises: 0005
Create Date: 2026-09-01 15:16:21.018559
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'ace257f86c3f'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('has_query', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('visits', sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'query_text')
    op.drop_column('visits', 'has_query')
    # ### end Alembic commands ###
