import sqlmodel
"""Add cryptographic hash to audit logs

Revision ID: bbb857bc24fb
Revises: 0005
Create Date: 2026-09-02 20:43:56.712941
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bbb857bc24fb'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('current_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_current_hash'), 'audit_logs', ['current_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_current_hash'), table_name='audit_logs')
    op.drop_column('audit_logs', 'current_hash')
    op.drop_column('audit_logs', 'previous_hash')
    # ### end Alembic commands ###
